let React = require('react');
let ReactDOM = require('react-dom');
import {CommentList,CommentForm} from './components/index.js';
let $ = require('jquery');
import style from "./scss/main.scss";
//let data = require( "./data/data.js");

let CommentBox = React.createClass({
    loadCommentsFromServer: function() {
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.log(this.props.url);
                console.log(status);
                console.log(err.toString());
                //console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },
    handleCommentSubmit: function(comment) {
        var comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        var newComments = comments.concat([comment]);
        this.setState({data: newComments});
        // TODO: submit to the server and refresh the list
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            type: 'POST',
            data: comment,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },
    getInitialState: function() {
        return {
            data: []
        }
    },
    componentDidMount: function() {
        this.loadCommentsFromServer();
        setInterval(this.loadCommentsFromServer, this.props.pollInterval);
    },
    render:function(){
        return(
           <div className="commentBox">
               <h1>Comments</h1>
               <CommentList data={this.state.data}/>
               <CommentForm onCommentSubmit={this.handleCommentSubmit} />
           </div>
        );
    }
});

ReactDOM.render(
    <CommentBox url="data.json" pollInterval={2000}/>,
    //React.createElement('h1',{name:'h1'},'hello world'),
    document.getElementById('content')
);

/*
// tutorial1-raw.js
var CommentBox = React.createClass({displayName: 'CommentBox',
    render: function() {
        return (
            React.createElement('div', {className: "commentBox"},
                "Hello, world! I am a CommentBox."
            )
        );
    }
});
ReactDOM.render(
    React.createElement(CommentBox, null),
    document.getElementById('content')
);*/
